### ISSUE TITLE
Venus.xvs.getXvsAccrued is undefined

### ISSUE THREAD

**Issue by Gojic** [VenusProtocol/venus-protocol#168]
Hello i am using snippets from venus.js docs 
`
const venus = new Venus(window.ethereum);
(async function () {
        const acc = await venus .xvs.getXvsAccrued(userWallet);
        console.log('Accrued', acc);
      })().catch(console.error);`

but getting Cannot read properties of undefined (reading 'getXvsAccrued') error. When i log venus i cant see xvs function nowhere.
this i see wneh i log out venus
 `borrow
: 
ƒ (e,t,o)
castVote
: 
ƒ (e,t,r)
castVoteBySig
: 
ƒ (e,t,o,i)
claimVenus
: 
ƒ (e)
createDelegateSignature
: 
ƒ (e,t)
createVoteSignature
: 
ƒ (e,t)
decimals
: 
{cBAT: 8, cCOMP: 8, cDAI: 8, cETH: 8, cREP: 8, …}
delegate
: 
ƒ (e,t)
delegateBySig
: 
ƒ (e,t,d,p,l)
enterMarkets
: 
ƒ (e,t)
exitMarket
: 
ƒ (e,t)
getMintableVAI
: 
ƒ (e,t)
getPrice
: 
ƒ (e,t)
getVAIMintRate
: 
ƒ (e)
mintVAI
: 
ƒ (e,t)
mintVAIGuardianPaused
: 
ƒ (e)
mintedVAIOf
: 
ƒ (e,t)
mintedVAIs
: 
ƒ (e,t)
redeem
: 
ƒ (e,t,o)
repayBorrow
: 
ƒ (e,t,o,i,s)
repayVAI
: 
ƒ (e,t)
repayVAIGuardianPaused
: 
ƒ (e)
supply
: 
ƒ (e,t,n,o)
vaiController
: 
ƒ (e)
vaiMintRate
: 
ƒ (e)
__esModule
: 
true
_network
: 
{id: 56, name: 'mainnet'}
_originalProvider
: 
Proxy {_events: {…}, _eventsCount: 0, _maxListeners: 100, _log: u, _state: {…}, …}
_provider
: 
t {_isSigner: true, provider: t, _index: 0, _address: null}
[[Prototype]]
: 
Object`

**Comment by coreyar** [comment]
From a quick glance it looks like the repo is out of date because I don't see this method. Instead it shows `Venus.venus.getVenusAccrued`. What version of the package are you using? It seems that when the project was handed off from the previous developers some updates to the js library were lost

You can find the venus.js code [here](https://github.com/VenusProtocol/venus-js)  If it is ok with you I'd like to move this conversation to that repo since it pertains to that repo and not the core protocol code
