### ISSUE TITLE
getAccountLiquidity(account) error

### ISSUE THREAD

**Issue by utkash** [VenusProtocol/venus-protocol#50]
the getAccountLiquidity(account) from Comptroller.sol isn't working properly.

I can't access my account from either venus.io or venus.finance.

I can't withdraw or send my vTokens.

Please check out the address to see if you can narrow down the issue:

0xdB4f7DB91482cE3f8393Db0725ef94Ba7237bBeF

**Comment by Dondudu** [comment]
See: https://github.com/VenusProtocol/venus-protocol/issues/46

**Comment by utkash** [comment]
Are there any updates to this issue? Would it be useful to reach our to the chain link team ?

**Comment by Dondudu** [comment]
Still broken. Chainlink team would need to set up an aggregator just for this, I don't think they would do that since the asset is technically defunct. 

There is a problem now that some accounts which have entered CAN are now undercollateralized and will suffer liquidation as soon as a price is set.

Venus team can probably rescue these accounts by writing a contract which atomically sets the price, liquidates the accounts, and returns the funds to the users. Though it might be easier to just let the accounts get liquidated and reimburse the users after.

**Comment by utkash** [comment]
Is there not a way to just disable CAN as collateral for my account? This is taking way long and I’m down over 200k since this issue has started

**Comment by Dondudu** [comment]
https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384#writeProxyContract

There is an exitmarket function here but it won't work for you since it calls getAccountLiquidity internally.

**Comment by kkirka** [comment]
Closing as stale. If your issue has not been resolved, please leave a comment
