### ISSUE TITLE
Real XVS price from VenusChainlinkOracle

### ISSUE THREAD

**Issue by xin866** [VenusProtocol/venus-protocol#71]
Hi,

I would like to know how Venus is getting the actual XVS price via the oracle. 
When I look to the function "getUnderlyingPrice(VToken vToken)"  inside VenusChainlinkOracle.sol code line 30, it seems like XVS price is manually set by the Admin and not retrieved dynamically from the chainlink data feed.  

Can someone please explain how the comptroller knows what't the realtime price of XVS without it manually being set by the admin? 

Many thanks!

**Comment by Kayaba-Attribution** [comment]
https://bscscan.com/address/0xd8b6da2bfec71d684d3e2a2fc9492ddad5c3787f#code

Contract on repo != onchain contract

`    function getUnderlyingPrice(VToken vToken) public view returns (uint) {
        string memory symbol = vToken.symbol();
        if (compareStrings(symbol, "vBNB")) {
            return getChainlinkPrice(getFeed(symbol));
        } else if (compareStrings(symbol, "VAI")) {
            return VAI_VALUE;
        } else if (compareStrings(symbol, "XVS")) {
            return prices[address(vToken)];
        } else {
            return getPrice(vToken);
        }
    }`

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by chechu** [comment]
As you can see in the [VIP-123](https://app.venus.io/#/governance/proposal/123), the oracle configured for [XVS](https://bscscan.com/address/0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63) is the [ChainlinkOracle](https://github.com/VenusProtocol/oracle/blob/main/contracts/oracles/ChainlinkOracle.sol) deployed at [0x1B2103441A0A108daD8848D8F5d790e4D402921F](https://bscscan.com/address/0x1B2103441A0A108daD8848D8F5d790e4D402921F), using the Chainlink price feed https://bscscan.com/address/0xBF63F430A79D4036A5900C19818aFf1fa710f206.

If there were a direct price configured (there isn't), it would be use (see it [here](https://github.com/VenusProtocol/oracle/blob/main/contracts/oracles/ChainlinkOracle.sol#L138)). Because there is not a direct price configured for XVS in the ChainlinkOracle, Chainlink is requested [here](https://github.com/VenusProtocol/oracle/blob/main/contracts/oracles/ChainlinkOracle.sol#L170)
